name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [8.0, 7.3]
        laravel: [7.*, 8.*, 9.*]
        stability: [prefer-lowest, prefer-stable]
        include:
          - laravel: 7.*
            testbench: '5.*'
            phpunit: '^8.5.8|^9.3.3'
            larastan: '^1.*'
            php-cs-fixer: '^3.4'
          - laravel: 8.*
            testbench: '6.*'
            phpunit: '^8.5.8|^9.3.3'
            larastan: '^1.*|^2.*'
            php-cs-fixer: '^3.4|^3.8'
          - laravel: 9.*
            testbench: '7.*'
            phpunit: '^9.5'
            larastan: '^2.*'
            php-cs-fixer: '^3.8'
        exclude:
          - laravel: 9.*
            php: 7.3

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/pest
